#!/bin/sh
lock() {
    icon="$HOME/.xlock/icon.png"
    tmpbg='/tmp/screen.png'
    
    (( $# )) && { icon=$1; }
    
    scrot "$tmpbg"
    convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
    convert "$tmpbg" "$icon" -gravity center -composite -matte "$tmpbg"
    i3lock -u -i "$tmpbg"
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && sudo pm-suspend
        ;;
    hibernate)
        lock && sudo pm-hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0